/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spartan2015_BaseJniClass */

#ifndef _Included_com_spartan2015_BaseJniClass
#define _Included_com_spartan2015_BaseJniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartan2015_BaseJniClass
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartan2015_BaseJniClass_destroy
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
