/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spartan2015_ExampleJni */

#ifndef _Included_com_spartan2015_ExampleJni
#define _Included_com_spartan2015_ExampleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartan2015_ExampleJni
 * Method:    hello
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_spartan2015_ExampleJni_hello
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif