/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spartan2015_PluginLoader */

#ifndef _Included_com_spartan2015_PluginLoader
#define _Included_com_spartan2015_PluginLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartan2015_PluginLoader
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartan2015_PluginLoader_init
        (JNIEnv *, jobject);

/*
 * Class:     com_spartan2015_PluginLoader
 * Method:    loadPluginNative
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_com_spartan2015_PluginLoader_loadPluginNative
        (JNIEnv *, jobject, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif