/* DO NOT EDIT THIS FILE - it is machine generated */
#include "handle.h"
/* Header for class com_spartan2015_Plugin */

#ifndef _Included_com_spartan2015_Plugin
#define _Included_com_spartan2015_Plugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartan2015_Plugin
 * Method:    getIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spartan2015_Plugin_getIdentifier
        (JNIEnv *, jobject);

/*
 * Class:     com_spartan2015_Plugin
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spartan2015_Plugin_getName
        (JNIEnv *, jobject);

/*
 * Class:     com_spartan2015_Plugin
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spartan2015_Plugin_getDescription
        (JNIEnv *, jobject);

/*
 * Class:     com_spartan2015_Plugin
 * Method:    getPluginVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_spartan2015_Plugin_getPluginVersion
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif